name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@3.0.177.219 << 'EOF'
            # Cài đặt Docker và Docker Compose (nếu cần)
            # sudo apt-get update
            # sudo apt-get install -y docker.io
            # sudo systemctl start docker
            # sudo systemctl enable docker
            # 
            # sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" \
            #   -o /usr/local/bin/docker-compose
            # sudo chmod +x /usr/local/bin/docker-compose

            # Kiểm tra
            docker --version
            docker-compose --version

            # Clone lại code nếu cần
            rm -rf Serverless-web
            git clone https://github.com/imLeHuyHoang/Serverless-web.git
            cd Serverless-web

            # Build & Run container
            sudo docker-compose up -d --build
          EOF
