name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@18.141.57.31 << 'EOF'
            # 1. Cài đặt Docker Compose Plugin
            if ! command -v docker-compose &> /dev/null; then
              echo "Installing Docker Compose Plugin..."
              sudo apt-get update
              sudo apt-get install -y docker-compose-plugin
            fi

            # 2. Install Node.js if not present
            if ! command -v node &> /dev/null; then
              echo "Installing Node.js..."
              curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi

            # 3. Clone or update repository
            cd ~
            if [ ! -d "Serverless-web" ]; then
              git clone https://github.com/imLeHuyHoang/Serverless-web.git
              cd Serverless-web
            else
              cd Serverless-web
              git pull origin main
            fi

            # 4. Stop any running containers
            echo "Stopping existing containers..."
            sudo docker compose down --volumes --remove-orphans || true

            # 5. Build and start new containers
            echo "Building and starting containers..."
            sudo docker compose up --build -d

            echo "Deployment completed!"
          EOF
