name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@18.141.57.31 << 'EOF'
            set -e
            
            echo "=== 1. Gỡ các gói Docker cũ (nếu có) ==="
            sudo apt-get remove -y docker docker.io containerd runc docker-compose || true
            sudo apt-get update

            echo "=== 2. Cài đặt Docker CE và Docker Compose Plugin ==="
            sudo apt-get install -y ca-certificates curl gnupg

            # Thêm GPG key cho Docker
            sudo install -m 0755 -d /etc/apt/keyrings
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
            sudo chmod a+r /etc/apt/keyrings/docker.gpg

            # Thêm Docker repository
            # Lưu ý: Nếu $(lsb_release -cs) bị sai, có thể thay bằng "jammy" (Ubuntu 22.04) hoặc phù hợp
            echo "deb [arch=\$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
              https://download.docker.com/linux/ubuntu \$(lsb_release -cs) stable" \
              | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

            sudo apt-get update
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

            echo "=== 3. Cài đặt Node.js (nếu chưa có) ==="
            if ! command -v node &> /dev/null; then
              echo "Installing Node.js..."
              curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi

            echo "=== 4. Clone hoặc pull code từ repo ==="
            cd ~
            if [ ! -d "Serverless-web" ]; then
              git clone https://github.com/imLeHuyHoang/Serverless-web.git
              cd Serverless-web
            else
              cd Serverless-web
              git pull origin main
            fi

            echo "=== 5. Dừng và xóa container cũ (nếu có) ==="
            sudo docker compose down --volumes --remove-orphans || true

            echo "=== 6. Build và chạy container mới ==="
            sudo docker compose up --build -d

            echo "Deployment completed!"
          EOF
