name: CI/CD Pipeline for React App

on:
  push:
    branches:
      - main  # Trigger CI/CD pipeline khi có push vào nhánh main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH for EC2 deployment
      run: |
        # Tạo thư mục .ssh nếu chưa có
        mkdir -p ~/.ssh

        # Lưu khóa SSH vào id_rsa
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        
        # Đảm bảo khóa có quyền truy cập đúng
        chmod 600 ~/.ssh/id_rsa

        # Thêm máy chủ EC2 vào danh sách known hosts
        ssh-keyscan -H ${{ secrets.HOST_DNS }} >> ~/.ssh/known_hosts

    - name: Copy code to EC2
      run: |
        # Sử dụng scp để sao chép mã nguồn lên EC2
        scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -r . ec2-user@${{ secrets.HOST_DNS }}:/home/ec2-user/${{ secrets.TARGET_DIR }}

    - name: Set up Docker on EC2 and deploy with Docker Compose
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_DNS }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Cài đặt Docker và Docker Compose trên EC2
          sudo yum update -y
          sudo yum install -y docker
          sudo systemctl start docker
          sudo systemctl enable docker

          # Cài đặt Docker Compose (nếu chưa có)
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

          # Build và chạy ứng dụng bằng Docker Compose
          cd /home/ec2-user/${{ secrets.TARGET_DIR }}
          sudo docker-compose up -d --build
