name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@3.0.50.73 << EOF
            set -e

            # 1) Gỡ Docker cũ (nếu có), cập nhật hệ thống
            sudo apt-get remove -y docker docker.io containerd runc docker-compose || true
            sudo apt-get update -y

            # 2) Cài Docker CE & Docker Compose Plugin
            sudo apt-get install -y ca-certificates curl gnupg
            sudo mkdir -p /etc/apt/keyrings
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
              | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
            echo "deb [arch=\$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu jammy stable" \
              | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            sudo apt-get update -y
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io \
              docker-buildx-plugin docker-compose-plugin

            # 3) Cài Node.js 20 nếu chưa có
            if ! command -v node &> /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi

            # 4) Clone hoặc pull code
            cd ~
            if [ ! -d "Serverless-web" ]; then
              git clone https://github.com/imLeHuyHoang/Serverless-web.git
              cd Serverless-web
            else
              cd Serverless-web
              git pull origin main
            fi

            # 5) Dừng container cũ và chạy container mới
            sudo docker compose down --volumes --remove-orphans || true
            sudo docker compose up --build -d

            echo "Deployment completed!"
          EOF
